name: "Release: build all ghostpdl binaries for wasm"
on: 
  push:
    tags:
    - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.63
          actions-cache-folder: emsdk-cache
      
      - name: Verify
        run: emcc -v

      - name: Build ghostpdl for wasm
        run: ./build/build.sh

      - name: Zip generated binaries
        run: |
          mkdir target
          cd build/ghostpdl/bin
          for base in $(ls | sed -e 's/\.[^.]*$//' | sort -u); do tar -cvf "$base.tar" $(ls "$base"*); gzip "$base.tar"; done
          mv *.tar.gz ../../../target          

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-binaries
          path: build/ghostpdl/bin
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
