name: "build ghostpdl binaries for wasm"
on: 
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.63
          actions-cache-folder: emsdk-cache

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ghostpdl for wasm
        run: ./build/build.sh

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-binaries
          path: build/ghostpdl/bin
